OSWP-Oreo/ewhamarket

flask_project2023-week8-4/1.html
flask_project2023-week8-4/templates/reg_items.html

1.html 만듦
1.html 생성: 1번 상품등록화면
- 페이지 제목~가격까지 html
- 내용을 적어주세요.

add 1.html

---

flask_project2023-week8-4/1~4/1.html

submit 버튼 "submit!" 에서 "등록하기"로
- .
- .

change submit button in 1.html

---

flask_project2023-week8-4/1~4/1-main.js
flask_project2023-week8-4/1~4/1.html
flask_project2023-week8-4/1~4/1~4 style.css
flask_project2023-week8-4/1~4/2.html
flask_project2023-week8-4/1~4/course-info.html

change 1.html, 2.html, 1~4 style.css add course-info.html
- 1.html class, id 이름 수정
- 2.html 검색창 -- (문서 타입 체크박스 외) 까지
- course-info.html에 1,2 중복 코드 추가
- 내용을 적어주세요.

change 1.html, 2.html, 1~4 style.css add course-info.html

---

flask_project2023-week8-4/1~4/1.html
flask_project2023-week8-4/1~4/2.html
flask_project2023-week8-4/1~4/regitem__course__faculty.html

college를 faculty로 수정
- 1.html, 2.html 내의 모든 college를 faculty로 변경
- regitem__course__college.html -> college를 faculty로 변경
- 내용을 적어주세요.

college를 faculty로 수정

---

flask_project2023-week8-4/8~10/login.html
flask_project2023-week8-4/8~10/ranking.html
flask_project2023-week8-4/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

update 8~10 pages to branch 9

---

flask_project2023-week8-4/1~4/2.html
flask_project2023-week8-4/1~4/3.html
flask_project2023-week8-4/1~4/change.txt
flask_project2023-week8-4/static/style.css

2.html 1차 완료
3.html 생성, 1차 완료
css에 색버튼 클래스 지정자 만듦
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 15 into main

---

flask_project2023-week8-4/1~4/4.html
flask_project2023-week8-4/1~4/change.txt
flask_project2023-week8-4/static/style.css

4.html 추가
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 16 to main

---

flask_project2023-week8-4/8~10/login.html
flask_project2023-week8-4/8~10/signup.html
flask_project2023-week8-4/static/style.css

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 17 to main

---

flask_project2023-week8-4/8~10/ranking.html
flask_project2023-week8-4/static/style.css

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 18 to main

---

flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/2.html
flask_project2023-week8-4/templates/1~4/3.html
flask_project2023-week8-4/templates/1~4/4.html

1~4.html  css&js link 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 22 to main

---

flask_project2023-week8-4/application.py
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/2.html
flask_project2023-week8-4/templates/1~4/3.html
flask_project2023-week8-4/templates/1~4/4.html
flask_project2023-week8-4/templates/1~4/item-card.html
flask_project2023-week8-4/templates/index.html

application.py에 1~4 출현하도록 수정
application.py 실행 시 1.html, 2.html, 3.html, 4.html 보이지 않던 오류 수정
- 1~4.html {%include %}문 내 경로 수정
- 내용을 적어주세요.

branch 23 to main

---

flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/2.html

style.css에서 .main-header text-align=center; 만 남김
1.html, 2.html <hr> id->class로 변경
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 28 to main

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/regitem__course__course-number.html
flask_project2023-week8-4/templates/1~4/regitem__course__course-type.html
flask_project2023-week8-4/templates/1~4/regitem__course__faculty.html

1.html 관련 css 추가: 과목명/학수번호까지
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 32 to main

---

flask_project2023-week8-4/templates/5~7/6.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 34 to main

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/regitem__course__faculty.html
flask_project2023-week8-4/templates/1~4/regitem__type.html

1.html에 대한 css 헤더 외 완성
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 35 to main

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/2.html
flask_project2023-week8-4/templates/1~4/item-card.html

- 1.html css 마무리, 
- 2. html css 필터까지 완료,  item card 진행중
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 36 to main

---

flask_project2023-week8-4/static/5~7style.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/5~7/5.html
flask_project2023-week8-4/templates/5~7/6.html
flask_project2023-week8-4/templates/5~7/review.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 37 to main

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/2.html
flask_project2023-week8-4/templates/1~4/item-card.html

2.html 관련 css 페이지네이션 외 1차 완성
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 38 to main

---

flask_project2023-week8-4/static/8~10style.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/8~10/ranking.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 41 to main

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/3btn.css
flask_project2023-week8-4/templates/1~4/3.html

css 버튼 생성
- 내용을 적어주세요.
- 내용을 적어주세요.

3.html버튼생성

---

flask_project2023-week8-4/templates/8~10/login.html
flask_project2023-week8-4/templates/8~10/ranking.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch45: 로그인, 회원가입 화면 헤더 수정 / 랭킹화면 포인트 표시 / 대학, 학과 드롭다운

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/4.html

4.html에 대한 1~4.css 수정완료
- 내용을 적어주세요.
- 내용을 적어주세요.

46.구매완료화면완성

---

flask_project2023-week8-4/application.py
flask_project2023-week8-4/templates/index.html

5,6,7.html 또한 application.py running 시 접근할 수 있도록 수정
- add route of 5~7 in applcation.py
- add link name of 5~7 in the index.html
- 내용을 적어주세요.

can access 5,6,7.html by running application.py

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/btn.css
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/2.html
flask_project2023-week8-4/templates/1~4/3.html
flask_project2023-week8-4/templates/1~4/4.html

1번화면 페이지제목 정렬
2번화면 필터제목 정렬
1,2,3,4화면 메인 여백
- 1번 main-header 쪽에 flex 이용
- 2번 filter쪽에 flex 이용
- 2,3,4 main tag에 padding  class 추가
- 내용을 적어주세요.

1페이지제목 2필터제목 정렬 및 1,2,3,4 여백

---

flask_project2023-week8-4/static/style.css

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 53: fix nav-bar padding and main-hr width

---

flask_project2023-week8-4/templates/8~10/login.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch55: fix duplicated header and nav-bar

---

flask_project2023-week8-4/static/8~10style.css
flask_project2023-week8-4/templates/8~10/login.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 56: fix mouse-hover, input arrangement, nav-bar href

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/3.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

57:rm .btn in style.css, add <a>  font color

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/3.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

58: complete 3.html

---

flask_project2023-week8-4/static/5~7style.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/5~7/6.html
flask_project2023-week8-4/templates/5~7/7.html
flask_project2023-week8-4/templates/5~7/review.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

6fix, style.css에 main-hr__padding 추가

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/2.html
flask_project2023-week8-4/templates/1~4/3.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

add 과목타입,단과대,학과and fix btn in 3.html

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/btn.css
flask_project2023-week8-4/templates/1~4/2.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

61: complete 2.html:fix btn, fix item-box rate align

---

flask_project2023-week8-4/static/5~7style.css
flask_project2023-week8-4/templates/5~7/5.html
flask_project2023-week8-4/templates/5~7/6.html

내용을 적어주세요.
- 별점 기능
- 페이지 5 6 수정
- 내용을 적어주세요.

branch 61 to main

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/2.html
flask_project2023-week8-4/templates/1~4/4.html

1~4.html button
- 내용을 적어주세요.
- 내용을 적어주세요.

63.cplt 2.html

---

flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/8~10/login.html
flask_project2023-week8-4/templates/8~10/signup.html

로그인, 회원가입 내비게이션 & 로고 링크 경로 오류 수정
- 1.html 을 /1~4/1 로 수정. 나머지 링크에도 동일 작업 반복 
- inde.html을 /index로 수정
- img 태그를 <a>로 감싸기
- 내용을 적어주세요.

63.fix navigation and logo link of login.html,  signup.html

---

flask_project2023-week8-4/static/5~7style.css
flask_project2023-week8-4/templates/5~7/5.html
flask_project2023-week8-4/templates/5~7/6.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 64 to main

---

flask_project2023-week8-4/static/5~7style.css
flask_project2023-week8-4/templates/5~7/6.html
flask_project2023-week8-4/templates/5~7/star.css

내용을 적어주세요.
- 페이지 6 픽스
- 페이지 5 별점 픽스
- 내용을 적어주세요.

branch 65 to main

---

flask_project2023-week8-4/static/style.css

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 66: add nav-bar mouse-hover

---

flask_project2023-week8-4/static/style.css

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch57: fix header padding

---

flask_project2023-week8-4/static/style.css

Reverts OSWP-Oreo/ewhamarket#73

Revert "branch57: fix header padding"

---

flask_project2023-week8-4/static/style.css

revert했던 브랜치 67작업다시함
- 내용을 적어주세요.
- 내용을 적어주세요.

69. header image padding 수정

---

flask_project2023-week8-4/static/1~4style.css

regitem 크기 수정. 1.html 완성
- 내용을 적어주세요.
- 내용을 적어주세요.

70.fix reg-item container size: mediaquery

---

flask_project2023-week8-4/static/5~7style.css
flask_project2023-week8-4/templates/5~7/7.html
flask_project2023-week8-4/templates/5~7/review.html

페이지 567 완성
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 72 to main. page 567 fin

---

flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/1.html
flask_project2023-week8-4/templates/1~4/2.html
flask_project2023-week8-4/templates/1~4/3.html
flask_project2023-week8-4/templates/1~4/4.html
flask_project2023-week8-4/templates/8~10/login.html
flask_project2023-week8-4/templates/8~10/signup.html
flask_project2023-week8-4/templates/header-and-nav.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

73: complete ver. fisrt

---

flask_project2023-week8-4/templates/8~10/ranking.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 73: fix ranking aline

---

flask_project2023-week8-4/templates/8~10/ranking.html

Reverts OSWP-Oreo/ewhamarket#81

Revert "branch 73: fix ranking aline"

---

flask_project2023-week8-4/templates/8~10/ranking.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch76: 오류수정

---

flask_project2023-week8-4/templates/8~10/ranking.html

ranking page table center align, fix warning message
- 내용을 적어주세요.
- 내용을 적어주세요.

78:ranking page table center align, fix warning message

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/5~7style.css

리뷰상세화면 이미지: 윈도우 커질 시 커지는 사항 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

79. fix reviewDetail img size: set a max size

---

flask_project2023-week8-4/templates/header-and-nav.html

11주차 index.html 내용 header-and-nav.html에 추가
- 11주차 강의자료 7페이지 내용 headr-and-nav.html에 추가. 주석 참고
- 내용을 적어주세요.

80.add-11주차 index.html 내용 header-and-nav.html에 추가

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/static/5~7style.css
flask_project2023-week8-4/templates/5~7/reg_reviews.html
flask_project2023-week8-4/templates/5~7/review_detail.html
flask_project2023-week8-4/templates/header-and-nav.html
flask_project2023-week8-4/templates/index.html

내용을 적어주세요.
-review.html 수정
-css 수정
- 내용을 적어주세요.

branch 83 to main

---

flask_project2023-week8-4/templates/8~10/login.html
flask_project2023-week8-4/templates/8~10/ranking.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch84: fix 8-10.style

---

flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

90: fix idcheck

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

write_review

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

reg_review_post

---

flask_project2023-week8-4/app.py

app.py수정
- app.py 오류수정
- 95-fix-order -> main
-

95-fix-order

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

get review data from DB

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

review page

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

review datail page

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

login_check,ave_star,keyword

---

flask_project2023-week8-4/database.py
flask_project2023-week8-4/templates/5~7/reg_reviews.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

keyword database

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

판매자 포인트 추가
-판매자도 포인트가 증가하도록
- 108-sellerPoint->main

108-sellerpoint

---

flask_project2023-week8-4/templates/5~7/individual_review.html
flask_project2023-week8-4/templates/5~7/reg_reviews.html
flask_project2023-week8-4/templates/5~7/review.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

branch 109 to main

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

fix review data

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

purchase item

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

fix 5-8 to 5~8

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

add sorting, major, college

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

delete all review page

---

flask_project2023-week8-4/templates/8~10/ranking.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

129-signup.html-jinja

---

flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

147-fix_college_dropdown

---

flask_project2023-week8-4/templates/8~10/ranking.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

152-ranking

---

flask_project2023-week8-4/static/1~4main.js
flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/item_reg.html
flask_project2023-week8-4/templates/1~4/view_item.html

아이템전체보기 이미지 사이즈 max-width 설정
- 내용을 적어주세요.
- 내용을 적어주세요.

152-fix-viewitem-imgsize

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

user_purchase

---

flask_project2023-week8-4/static/8~10style.css
flask_project2023-week8-4/templates/8~10/ranking.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

157-fix-ranking.html

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/detail.html

상품세부화면 이미지 크기 및 정렬 수정: 중앙정렬, 서브이미지와의 크기 통일(제일 처음 설정)
- 내용을 적어주세요.
- 내용을 적어주세요.

159-fix-detail-img

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

fix reference

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

fix ~ to -

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/btn.css
flask_project2023-week8-4/templates/1~4/view_item.html

전체상품조회 리뷰 버튼 <a> 태그에서 <button>으로 변경
- 내용을 적어주세요.
- 내용을 적어주세요.

169-fix-viewItem-reivewBtn

---

flask_project2023-week8-4/templates/1~4/view_item.html

상품전체보기화면(view_item.html)에 검색하기 버튼 추가
- 내용을 적어주세요.
- 내용을 적어주세요.

175-add-searchitem-btn

---

flask_project2023-week8-4/templates/1~4/view_item.html

전체상품보기 필터의 리셋 버튼 작동되록 수정
- view_item.html의 filter 섹션 <section> tag into <form> tag 하여 <input type="reset">을 form 안으로 넣음
- 하위 form 태그는 div 태그로 변경
- 내용을 적어주세요.

177-viewItem-filter-reset

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

fix user_purchase_history

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

fix to get_purchase_history

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

fix mypage data

---

flask_project2023-week8-4/templates/8~10/ranking.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

196-collegesort-btn

---

flask_project2023-week8-4/app.py
flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

add timestamp in review

---

flask_project2023-week8-4/templates/8~10/ranking.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

204-department-session

---

flask_project2023-week8-4/templates/1~4/regitem__type.html

item_type.html에서 value 값을 영문에서 한국어로 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

213-rename-itemtype-value

---

flask_project2023-week8-4/templates/1~4/item_reg.html

상품등록 시 course type: major, liberal(?)을 한국어로(전공/교양) 변경 -> 상품등록 시 데이터베이스에 한국어로 입력됨
- 내용을 적어주세요.
- 내용을 적어주세요.

215-fix-coursetype-value

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/view_item.html

상품세ㅜㅂ화면에서 filter delete
- 내용을 적어주세요.
- 내용을 적어주세요.

221-delete-filter

---

flask_project2023-week8-4/templates/1~4/view_item.html

태그 필드에서 '#'가 없을 시 '#'를 앞에 붙여서 출력하도록 함
- 내용을 적어주세요.
- 내용을 적어주세요.

223-add-tag-formatting

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/btn.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/detail.html
flask_project2023-week8-4/templates/1~4/item_reg.html
flask_project2023-week8-4/templates/1~4/view_item.html

색변수변경
- 내용을 적어주세요.
- 내용을 적어주세요.

229-change-color-and-title-size

---

flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/view_item.html
flask_project2023-week8-4/templates/index.html

- navbar에서 포인트 클릭 시 랭킹으로 이동하게 경로 수정
- navitem의 크기 균일하도록 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

230-fix-navitemsize

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

pagination change to start 1

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

235 fixpagination

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

fix proportion

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

change login message

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/btn.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/detail.html
flask_project2023-week8-4/templates/1~4/item_reg.html
flask_project2023-week8-4/templates/1~4/view_item.html

- 아이템 전체보기, 아이템세부보기화면에서 별점 표시 진자문 추가, 별점 표시 레이아웃 변경
- 아이템등록 시 가격 상한 설정: 십만까지 등록 가능
- 내용을 적어주세요.
- 내용을 적어주세요.

246-fix-viewitem-star-and-set-maxprice

---

flask_project2023-week8-4/static/1~4style.css

- 구매완료페이지 테이블 헤드 영역 글자색 및 굵기 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

247-fix-order_item-font

---

flask_project2023-week8-4/static/style.css

- 상품등록화면에서 스크롤 시 몇몇 인풋창이 내비게이션 바 위로 올라오는 현상 수정
- 내비게이션 바의 투명도 90퍼로 추가
- 내용을 적어주세요.
- 내용을 적어주세요.

248-fix-nav-zindex-and-opacity

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/style.css

- 내비게이션 바 : 뒷쪽 흐리기 효과 추가 (일부 브라우저에서 지원 안 함)
- 상품전체보기 화면 검색창-드롭다운들 테두리 둥글게
- 내용을 적어주세요.
- 내용을 적어주세요.

250-add-nav-bgblur/fix-viewitem-searchSelectBorder

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/static/style.css
flask_project2023-week8-4/templates/1~4/item_reg.html

item_reg.html(상품등록화면) 레이아웃 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

252-fix-regitem-layout

---

flask_project2023-week8-4/templates/1~4/view_item.html

- view_item.html에 카테고리별 검색 기능을 위한 onchange 추가
- coursetype 'major' 'libral'을 '전공', '교양'으로 수정
- 내용을 적어주세요.
- 내용을 적어주세요.

253-add-sortingFunc-viewitem

---

flask_project2023-week8-4/templates/8~10/ranking.html
flask_project2023-week8-4/templates/8~10/signup.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

256-ranking-nickname

---

flask_project2023-week8-4/database.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

database review

---

flask_project2023-week8-4/app.py

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

269-maxrankingpoint2

---

flask_project2023-week8-4/templates/index.html

내비게이션 바의 로고를 클릭하면 홈 화면(전체상품보기)로 이동
- 내용을 적어주세요.
- 내용을 적어주세요.

274-add-route-to-logo

---

flask_project2023-week8-4/static/1~4style.css
flask_project2023-week8-4/templates/1~4/detail.html
flask_project2023-week8-4/templates/1~4/item_reg.html

rm review reg btn in detail.com, add guid about uploading in itemreg
- 내용을 적어주세요.
- 내용을 적어주세요.

276-rm review reg btn in detail.com, add guid about uploading in itemreg

---

flask_project2023-week8-4/static/8~10style.css
flask_project2023-week8-4/templates/8~10/ranking.html

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

279-ranking-inner-center
